#!/usr/bin/env bash
# Configures localhost to resolve to 127.0.0.2 and facebook.com to 8.8.8.8
cp /etc/hosts /tmp/hosts_tmp
sed 's/127.0.0.1\(.*\)localhost/127.0.0.2\1localhost/' /tmp/hosts_tmp > /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts
